# By default, NotRemoteRunner is used when RAILS_ENV == 'test'.
#
# You can pass options to memcached client by nesting the key value pairs
# under 'memcache_options'.
#
# You can also use a cluster of Starlings. Simply give a comma separated
# list of server:port, server:port, server:port values to listens_on. 
#
# 
# For the amqp client, you can control the type of marshaling by setting:
# ymj: yaml or ymj: marshal.  It defaults to marshal if nothing is set.  

# Example:
#
# defaults: &defaults
#   invoker: thread_pool_poller
#   pool_size:  10
#   sleep_time: 1
#   reset_time: 15
#   memcache_options:
#     multithread: true
#
# development:
#   <<: *defaults
#   listens_on: localhost:12345
#
# test:
#   <<: *defaults
#   listens_on: localhost:44244
#
# staging:
#   <<: *defaults
#   listens_on: localhost:22122
#
# production:
#   <<: *defaults
#   listens_on: magrathea:22122, rupert:22122
#
production:
  listens_on: localhost:15151

development:
  listens_on: localhost:22122
  
test:
  listens_on: localhost:12345
